SELECT 
      [Product Name]
      ,[Category Name]
	  , CONCAT([Customer Fname],' ',[Customer Lname]) AS [Customer Name]
      ,[Department Name]
      ,[Customer Segment]
      ,[Customer Id]
	  ,[Order Id]
	  ,[Product Card Id] AS [Product Id]
      ,[order date (DateOrders)] AS [Order Date & Time]
      ,[shipping date (DateOrders)] AS [Shipping Date & Time]
      ,[Market]
      ,[Order City]
      ,[Order Country]
      ,[Order Region]
      ,[Order State]
      ,[Order Status]
	  ,[Type]
	  ,[Order Item Discount]
      ,[Order Item Quantity] AS Quantity
      ,[Sales]
      ,[Order Item Total]
      ,[Order Profit Per Order]
      ,[Product Price]
      ,[Benefit per order] AS [Profit / Order]
      ,[Sales per customer] AS [Sales / Customer]
	  ,[Delivery Status]
	  ,[Days for shipping (real)]  AS [Actual Shipping Days]
      ,[Days for shipment (scheduled)] AS [Scheduled Shipping Days]
      ,[Shipping Mode]

  FROM [supplytable].[dbo].[SupplyChainDataset]


